Repository AxonFramework/extension-kafka, pull requests merged in 2019-10, with the labels that each got.

#11 Support of configurable event processors mode to be used for Kafka message publication.
  kafka-axon-example/README.md
  kafka-axon-example/docker-compose.yaml
  kafka-axon-example/pom.xml
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/KafkaAxonExampleApplication.kt
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/api/Commands.kt
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/api/Events.kt
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/client/BankClient.kt
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/core/BankAccount.kt
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/handler/BankEventHandler.kt
  kafka-axon-example/src/main/resources/application-subscribing.yml
  kafka-axon-example/src/main/resources/application-tracking.yml
  kafka-axon-example/src/main/resources/application.yml
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/KafkaProperties.java
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfiguration.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfigurationTests.java
  kafka-spring-boot-starter/pom.xml
  kafka/pom.xml
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/HeaderUtils.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactory.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisher.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaSendingEventHandler.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/KafkaIntegrationTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/FetchEventsTaskTests.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/SortedKafkaMessageBufferTests.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryTests.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisherBuilderTests.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisherTests.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#14 Minor Kafka Event Publisher Adjustments
  .travis.yml
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfiguration.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfigurationTest.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaEventPublisher.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaSendingEventHandler.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/DefaultKafkaMessageConverterTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/KafkaIntegrationTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisherTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#13 Fix KafkaTrackingToken#covers
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/KafkaTrackingToken.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/KafkaTrackingTokenTests.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#16 [#8] Avoid closing non-transactional Producer after a couple of usages
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactory.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug
