Repository AxonFramework/extension-kafka, pull requests merged in 2021-07, with the labels that each got.

#158 [#34] Introduce a KeyDeserializer for the KafkaTrackingToken
  kafka/pom.xml
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/KafkaTrackingToken.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/TopicPartitionDeserializer.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/TrackingTokenConsumerRebalanceListener.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/KafkaTrackingTokenSerializationTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/KafkaTrackingTokenTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/TestSerializer.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/TopicPartitionDeserializerTest.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#140 Provide default value for `defaultTopic` property.
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/KafkaProperties.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfigurationTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#167 [#6] Update to Axon Framework 4.5
  .run/Kafka Axon Example - PooledStreaming Producer and Consumer.run.xml
  .run/Kafka Axon Example - PooledStreaming Producer and Subscribing Consumer.run.xml
  .run/Kafka Axon Example - PooledStreaming Producer and Tracking Consumer.run.xml
  .run/Kafka Axon Example - Subscribing Producer and Consumer.run.xml
  .run/Kafka Axon Example - Subscribing Producer and Tracking Consumer.run.xml
  .run/Kafka Axon Example - Tracking Producer and PooledStreaming Consumer.run.xml
  .run/Kafka Axon Example - Tracking Producer and Subscribing Consumer.run.xml
  README.md
  kafka-axon-example/README.md
  kafka-axon-example/pom.xml
  kafka-axon-example/src/main/kotlin/org/axonframework/extension/kafka/example/KafkaAxonExampleApplication.kt
  kafka-axon-example/src/main/resources/application-pooled-streaming-consumer.yml
  kafka-axon-example/src/main/resources/application-pooled-streaming-producer.yml
  kafka-axon-example/src/main/resources/application.yml
  kafka-spring-boot-autoconfigure/pom.xml
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/KafkaProperties.java
  kafka-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfiguration.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/KafkaPropertiesTest.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/SubscribingProducerIntegrationTest.java
  kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfigurationTest.java
  kafka-spring-boot-starter/pom.xml
  kafka/pom.xml
  kafka/src/main/java/org/axonframework/extensions/kafka/configuration/KafkaMessageSourceConfigurer.java
  kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisher.java
  kafka/src/main/resources/META-INF/spring-devtools.properties
  kafka/src/test/java/org/axonframework/extensions/kafka/configuration/KafkaMessageSourceConfigurerTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/streamable/TrackingTokenConsumerRebalanceListenerIntegrationTest.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement
