Repository AxonFramework/extension-kafka, pull requests merged in 2021-01, with the labels that each got.

#96 Remove spring core overrides and upgrade Spring Boot to 2.4.1
  kafka-axon-example/pom.xml
  kafka/pom.xml
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Dependency Upgrade

#105 Enhancement/readme md
  README.md
Labels: Ideal for Contribution, Priority 4: Would, Status: In Progress, Type: Enhancement

#93 [#92] testPublishMessagesWithAckModeNoUnitOfWorkShouldBePublishedAndReadSuccessfully sometimes fails
  kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/KafkaPublisherTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Bug
